os:
    - linux

language: node_js
    - "10.15.0"

jdk:
    - oraclejdk8

env:
    - NODE_VERSION="10.15.0"

before_script:
    - npm install -g @angular/cli prettier

script: (mvn clean test package)

branches:
    only:
        - develop
        - /^release\/.*$/

before_deploy:
    - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
    - export BUILD_VERSION=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')
    - export TRAVIS_TAG=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')-$(date +%Y%m%d%H%M%S)
    # - export LIBRARY_ARTIFACT=$(find . -name comixed-library-*.jar)
    # - export TASKS_ARTIFACT=$(find . -name comixed-tasks-*.jar)
    # - export REST_API_ARTIFACT=$(find . -name comixed-rest-api-*.jar)
    # - export FRONTEND_ARTIFACT=$(find . -name comixed-frontend-*.jar)
    # - export IMPORTER_ARTIFACT=$(find . -name comixed-importer-*.jar)
    - export APP_ARTIFACT=$(find . -name comixed-app-*.jar)
###################################
# NOT GOING TO TAG THINGS FOR NOW #
###################################
#    - git config --local user.name "Darryl L. Pierce"
#    - git config --local user.email "mcpierce@gmail.com"
#    - git tag $TAG_NAME

deploy:
    - provider: releases
      api_key: $GITHUB_AUTH_TOKEN
      file_glob: true
      file:
        # - ${LIBRARY_ARTIFACT}
        # - ${TASKS_ARTIFACT}
        # - ${REST_API_ARTIFACT}
        # - ${FRONTEND_ARTIFACT}
        # - ${IMPORTER_ARTIFACT}
        - ${APP_ARTIFACT}
      skip_cleanup: true
      keep-history: true
      overwrite: true
      on:
        branch: develop
    - provider: releases
      api_key: $GITHUB_AUTH_TOKEN
      file_glob: true
      file:
        # - ${LIBRARY_ARTIFACT}
        # - ${TASKS_ARTIFACT}
        # - ${REST_API_ARTIFACT}
        # - ${FRONTEND_ARTIFACT}
        # - ${IMPORTER_ARTIFACT}
        - ${APP_ARTIFACT}
      skip_cleanup: true
      keep-history: true
      overwrite: true
      on:
        branch: release\/.*$/

cache:
    directories:
        - ~/.m2/repository
        - comixed-frontend/node_modules
